### ISSUE TITLE
使用 Wiki 还是 GitHub Pages

### ISSUE THREAD

**Issue by TieBaMma** [TieBaMma/InstallTutorial#4]
WIKI的主要优点是能用MarkDown写，比直接改HTML还是要方便不少的……

另外，我姑且已经把WIKI的编辑权限给打开了……

**Comment by StephDC** [comment]
其實要不然把 MarkDown 扔進來 repo 然後每次更新 Wiki 時順便把 GitHub.io 這個 MarkDown 同步，然後使用 [MarkDown 轉 HTML 程式](http://daringfireball.net/projects/markdown/) 弄回 html 版？
最後一步弄回 html 這個可以弄個小 bash 腳本輕鬆搞定倒是

**Comment by Lemmingh** [comment]
@TieBaMma

在 2019 年这个时间点上看，我赞同 **StephDC** 的观点。显然，**Markdown 易于编辑和检查**，就像您说的那样。而且，编辑 Markdown 可以把主要精力放在文字安排和文档结构上，进而**改善文档的排版**。

在我看来，当前最佳解决方案有 3 种：

1. 在 repo 中存储 Markdown 源文件，并且每次编辑后同步生成 HTML 文件，一起 commit。
2. 改用 Jekyll，在 repo 中存储网站源文件（包含 Jekyll 的配置文件和 Markdown），[交由 GitHub Pages 自动生成网站](https://help.github.com/articles/using-jekyll-with-pages)。
3. 在 repo 中存储 Markdown 源文件，交由用户的浏览器自动生成内容主体。

我个人略倾向于方案 1。我认为，就本项目的特点来说，最终呈现单纯 HTML 网页是较合适的。不过，后文会看到，仍然有必要引入一点 JavaScript。

但是，我**推荐**方案 3。它非常有竞争力，因为 [Marked] 和 [markdown-it] 之类的库很快，延迟极小，而且，部署远远比方案 1 和 2 简单，空间消耗也明显很小。*此外，现在应该没有人禁用 JavaScript，不必担心无法加载。*

---

## 常见的 Markdown 编译器（按首字母排序）

* [kramdown](https://kramdown.gettalong.org/): 基于 Ruby
* [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one): [VS Code](https://code.visualstudio.com/) 扩展
* [markdown-it]: 支持 Node.js 和 Web 浏览器
* [Marked]: 支持 Node.js 和 Web 浏览器
* [MarkdownViewer++](https://github.com/nea/MarkdownViewerPlusPlus): [Notepad++](https://notepad-plus-plus.org/) 插件
* [Python-Markdown](https://github.com/Python-Markdown/markdown): 基于 Python
* [PHP Markdown](https://github.com/michelf/php-markdown): 基于 PHP

> 我个人使用 VS Code 配合 Markdown All in One 和 [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) 扩展来编辑 Markdown。

[markdown-it]: https://github.com/markdown-it/markdown-it
[Marked]: https://github.com/markedjs/marked

---

## 迁移前的准备工作

写个 `README.md` 来确定**编辑规范**。主要工作是约定

* repo 结构
* 编码
* 书写风格
* 网页样式

> 值得注意的是，需要在 `README.md` 中提醒编辑者：
> 磁力链接 (magnet) 应当以 HTML `a` tag 嵌入，或者以 code block 呈现，以防编译错误。

---

## 具体迁移流程（方案 3）

本方案会修改 `index.html`，新增 `content.md`。

### 1. 把内容主体迁移到 Markdown

把 `index.html` 的 `<section class="main-content">` 中的内容迁移到 `content.md`。
但 `<footer class="site-footer">` 应该保留在 `index.html` 中，移到 `main-content` 下方。

### 2. 处理 `index.html`

> 下文使用 [Marked] 实现。

首先在 `head` 中增加

```html
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
```

之前已经把 `<section class="main-content">` 中的内容迁移了，于是，现在添加一段 JavaScript 生成其内容。

```html
<section class="main-content">Loading... JavaScript is required.</section>

<script>
'use strict';

(function () {
  const mainContainer = document.querySelector('section.main-content');

  function onFetchError(reason) {
    mainContainer.textContent = 'Network errors occurred.\nResaon: ' + reason + '\nRetry...';
    buildContent();
  }

  function buildContent() {
    fetch('/content.md').then(res => {
      if (res.ok)
      {
        res.text().then(markdownText => mainContainer.innerHTML = marked(markdownText));
      } else
      {
        onFetchError(res.status);
      }
    }, onFetchError);
  }

  buildContent();
})();
</script>
```

> **注意**
>
> * 此处假定本项目的编辑者都没有恶意行为。如果担心安全问题，就再用 [DOMPurify](https://github.com/cure53/DOMPurify) 处理 Marked 的输出。
> * 如果考虑上古（ES6 以前）兼容性，请把 JavaScript 代码中的 `let` 和 `const` 都改为 `var`，`fetch` 改用 `XMLHttpRequest`。
> * jsDelivr 与 Cloudflare 等合作，提供中国大陆的 CDN 支持，加载通常很快。
> * 不一定在 `head` 中加载 `marked.min.js`，出于美观考虑，可以把它紧贴在 `<section class="main-content">` 之前。

### 测试

使用 Python SimpleHTTPServer (`python -m http.server 80 --bind localhost`) 搭建测试服务器；
网络不节流；
加载一个与本项目相等的网站；
使用 Firefox 68.0.2 (64 位) 的 开发者工具 分析性能。

结果如下

本方案与 `https://tiebamma.github.io/InstallTutorial/` 相比，

**没有缓存**：
文件大小、传输量、传输耗时、响应时间均**无明显差异**。（传输量差异在 几十KB，传输耗时差异在 几百ms）。
增量主要来自 JS（加载 `marked.min.js`）和 XHR（加载 `content.md`），而本方案中 HTML 明显缩减又对总量有益。

**初次缓存**：
文件大小、传输量、传输耗时、响应时间均**无明显差异**。（传输量差异在 几十KB，传输耗时差异在 几十ms）。
看上去，再次访问网站时，所有文件都从浏览器缓存读取。

---

## 具体迁移流程（方案 1）

本方案会修改 `index.html`，新增 `content.md` 和 `content.html`。

### 1. 在 `README.md` 中强制实施一套操作流程

例如，若使用 VS Code，只要写好 `.vscode/settings.json` 配置文件，强制风格和生成网页就是**自动**的，后续的编辑者只需把精力放在 Markdown 上。

### 2. 把源文件迁移到 Markdown

这里，我**推荐**的方案是：将内容主体分离出来，建立文件 `content.md`；在 `index.html` 中使用 `<iframe>` 呈现 `content.html`。*基于本文中所述的原因，仍需要在 Markdown 中内联少量 HTML，但应该不会影响编辑体验。*

> 另外一种方案是，建立文件 `index.md`。把 `<section class="page-header">` 等部分内联在 `index.md` 中。
> 但我不非常建议那种方案，因为它会大量破坏 Markdown 的易用性，导致跟直接编辑 HTML 没有区别。

先处理 `index.html`。把 `<section class="main-content">` 中的内容迁移到 `content.md` 中，原位置替换为

```html
<iframe src="content.html" referrerpolicy="no-referrer" style="border: none; display: block; position: fixed; left: 0; top: 10vh; height: 90vh; width: 100vw; z-index: -1;">main-content</iframe>
```

> **注意**
>
> 这个 `iframe` 内联了以下样式
>
> ```css
> {
> border: none;
> display: block;
> position: fixed;
> left: 0;
> top: 10vh;
> height: 90vh;
> width: 100vw;
> z-index: -1;
> }
> ```

与之配合，对 `<section class="page-header">` 做如下修改：

首先，追加样式以调整 `index.html`

```css
/**
  * The `.page-header` occupies the top 10% of the viewport.
  * The `.main-content > iframe` occupies the bottom 90% of the viewport.
  */

/* The combination of `max-height` and `min-height` allows the animations to be calculated correctly. */
.page-header {
  transition: all 0.3s ease-in;
  overflow: hidden;
  display: flex;
  max-height: 10vh;
  min-height: 10vh;
  align-items: baseline;
  justify-content: space-around;
  flex-wrap: wrap;
  animation: shrink_page_header 2s ease-in 0s;
}

.page-header:not(:hover) {
  padding-bottom: 0;
  padding-top: 0;
}

/* Provide an acceptable experience, especially on mobile. */
.page-header:hover,
.page-header:active,
.page-header:focus-within {
  overflow: auto;
  display: block; /* Activates styles in `stylesheet.css`. */
  max-height: 50vh;
}

/* To show the user the logic of the header. */
@keyframes shrink_page_header {
  from { max-height: 100vh; }
  to { max-height: 10vh; }
}
```

接着，删除无用元素，以避免 `section.page-header` 在 `flex` 时排版异常

```html
<h2 class="project-tagline"></h2>
```

最后，我注意到，可能误触 `.page-header` 中的 `a.btn`。该误触是一个可能性非常小的情况，需要在**狭小的触控屏**上操作才出现，而且即使发生也对用户体验没有很大影响。
解决方案是，JavaScript 侦听事件，在焦点离开 `.page-header` 时，自动滚动它至其顶部。鉴于您在贴吧中指出，人们都使用电脑访问本项目，我暂不处理。

此外，`content.md` 中需要使用 `<script>` 引入我后文 **超链接问题** 中将要提到的 JS。中间正常地书写。
还要基于 `stylesheet.css` 为 `content.html` 设置样式。

那些不重要的细节，现在暂不讨论。

这里还有一个**问题**：
文档末尾的 `<footer class="site-footer">` 页脚应该放在哪里？

* 应该内联到 `content.md` 的末尾呢
* 还是塞进 `index.html` 的 `.page-header` 中呢

---

## 超链接问题

本项目存在一些棘手的问题，比如**超链接**。目前，所有的链接默认都在当前页面的 context 中打开，有点影响阅读体验。尤其是方案 1，由于引入了 `iframe`，这会导致更加反直觉的现象。

> 顺便一提，`.page-header` 中的那两个 `Download btn` 的链接可能需要修正：
> 把 `master` 换成 `gh-pages`。

考虑到 `a` tag 数量众多。当前最佳解决方案是使用 JavaScript 批量修改 DOM，以强制所有的指向外部的超链接都在新窗口中打开。只需添加以下

```javascript
'use strict';

// To force links to be opened in a new context.
// Only process links other than URL fragments. (A URL fragment points to an internal target location within the current document.)
// Some odd links might be processed accidently as well. However, we don't have to worry because those are usually deprecated usages.
// ! Caution: `aLink.href` returns full URI. Do NOT use it.
window.onload = function () {
  const aTags = document.getElementsByTagName('a');
  for (const aLink of aTags)
  {
    if (aLink.getAttribute('href') && aLink.getAttribute('href').match(/^[^#].*/))
    {
      aLink.target = "_blank";
      aLink.rel = "noreferrer noopener";
    }
  }
}
```

考虑到复用，假定把上述 JavaScript 代码写在一个名为 `all.js` 的文件中，那么只需在每个 HTML 文档中添加

```html
<script src="all.js"></script>
```

另外，偷个懒，我还想在 `all.js` 中加一段

```javascript
// Sets the base language to Chinese (Simplified). Using JS, we dont't have to check each HTML document every time.
document.documentElement.lang = 'zh-Hans';
```

---

## 对本项目内容的讨论

### 1. 处置失效和重定向的链接

据我观察，本项目中存在许多疑似**失效的链接**，*似乎都是百度造成的问题*，比如

* <http://tieba.baidu.com/p/2570976088>
* <http://tieba.baidu.com/p/4024190694>
* <http://tieba.baidu.com/p/4172398243>
* <http://tieba.baidu.com/p/3204136180>
* <http://pan.baidu.com/share/link?shareid=188221&uk=1661347987>

请问，**如何处置它们**？您是否有打算迁移这些内容？（毕竟百度贴吧隐藏帖子的行为可能会长期存在）

此外，**有道云笔记**似乎又更改了它们的 URL 格式，也许有必要更新文档中相关的分享链接。

### 2. 有关版本选择的提示语

2016-11-07，您在 [Issue 7](https://github.com/TieBaMma/InstallTutorial/issues/7#issuecomment-258771459) 中提到

> 对于版本8旁边那句“推荐使用这个版本”我一直在犹豫是不是该去掉

现在来看，那句话可以与其他几句话整合为一段。放在整个 **下载地址** 部分的开头，大致呈现如下

> **注意**
>
> 英文版也可以调出中文提示，但是它没有中文帮助。只有带了**中文帮助**的才叫中文版！
>
> ---
>
> Linux 版无中文版，自行汉化的方法可参考[这帖](http://tieba.baidu.com/p/4024190694)。
>
> ---
>
> Windows 版对 HDPI 显示器的支持不佳，导致显示模糊。该问题可能会长期存在。可以通过设置 **高 DPI 缩放替代** 为 **应用程序**，以及调节 Wolfram 笔记本的缩放等措施来暂缓。
>
> ---
>
> 没有太多需求的初学者可以考虑先上手版本 8，参考[这帖](http://tieba.baidu.com/p/3204136180)。*仍请注意兼容性等问题。*
>
> ---
>
> **如无特殊原因请不要选择过老的版本！**
>
> 1. 较老的 Mathematica 与现代的有许多不兼容之处。
> 2. 较老的 Mathematica 往往与现代的计算机不兼容，尤其是 Mac。
> 3. 在版本 7 以前，Mathematica 无官方中文版。
> 4. 早期 MMA 的自带文档非常简略。
> 5. [绘图和动画等功能在版本 6 时有过重大修改](https://note.youdao.com/noteshare?id=0c2719208239696d61182199327bd38c)。

至于剩下的几条与特定版本*强绑定*的提示，保留在原处。
您看如何？

---

如果您同意的话，我可以实施上述迁移流程，并在大约 2 个月后提交一个 PR。
